### ISSUE TITLE
Uploading attachments with filenames > 100 chars raises DatabaseError

### ISSUE THREAD

**Issue by barsch** [hpoul/sct-communitytools#3]
This should be properly catched by renaming/shorten the filename automatically.

``` python
Traceback (most recent call last):

  File "/home/django/python/lib/python2.6/site-packages/Django-1.4.1-py2.6.egg/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/home/django/python/lib/python2.6/site-packages/django_sct-0.7-py2.6.egg/sphene/sphboard/views.py", line 334, in post
    attachment.save()

  File "/home/django/python/lib/python2.6/site-packages/Django-1.4.1-py2.6.egg/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)

  File "/home/django/python/lib/python2.6/site-packages/Django-1.4.1-py2.6.egg/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)

  File "/home/django/python/lib/python2.6/site-packages/Django-1.4.1-py2.6.egg/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)

  File "/home/django/python/lib/python2.6/site-packages/Django-1.4.1-py2.6.egg/django/db/models/query.py", line 1576, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)

  File "/home/django/python/lib/python2.6/site-packages/Django-1.4.1-py2.6.egg/django/db/models/sql/compiler.py", line 910, in execute_sql
    cursor.execute(sql, params)

  File "/home/django/python/lib/python2.6/site-packages/Django-1.4.1-py2.6.egg/django/db/backends/postgresql_psycopg2/base.py", line 52, in execute
    return self.cursor.execute(query, args)

DatabaseError: value too long for type character varying(100)
```

**Comment by hpoul** [comment]
FWIW this is still a bug in django itself actually: https://code.djangoproject.com/ticket/13314 i guess in SCT this could also be fixed, but a workaround might be to set board_attachments_upload_to to an empty string and hence allow the normal validation to kick in.

**Comment by barsch** [comment]
thanks, closing for now - feel free to reopen if you want to tackle it within SCT

**Comment by hpoul** [comment]
@barsch i guess i'll might fix it, because file upload with django 2 is generally broken right now, so it might fit into #5 :) btw. are you using SCT? i'm pretty much getting back into trying to maintain it.. at least i'm now again using it on my personal blog :)

**Comment by barsch** [comment]
sorry I gave up on it - I needed a plain forum solution and djangobb seemed to be the "better" supported platform at the time of the switch. However, I have to switch in the future again as djangobb sees not to much love anymore.

So if you can decouple the forum from everything else I would consider it ;) 
A strong candidate for me atm is this one: https://github.com/ellmetha/django-machina
